
package Formulario;

import ClaseConectar.Conectar;
import Clases.fecha;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class cierrediario extends javax.swing.JInternalFrame {
    fecha fecha=new fecha();
    public static String bandera_cierrediario;
    public cierrediario() {
        initComponents();
        txtfecha.setText(fecha_actual());
    }
    
    public static String fecha_actual(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha= new SimpleDateFormat("YYYY-MM-dd");
        return formatoFecha.format(fecha);
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        lb_fech_act_cierred1 = new javax.swing.JLabel();
        lb_id_recep_cierr_d1 = new javax.swing.JLabel();
        lb_turn_cierr_d1 = new javax.swing.JLabel();
        cmbturno = new javax.swing.JComboBox<>();
        txtrecepcionista = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        lb_mont_reca_cierr_d1 = new javax.swing.JLabel();
        lb_montN_cierr_d1 = new javax.swing.JLabel();
        lb_gast_cierr_d1 = new javax.swing.JLabel();
        txtrecaudado = new javax.swing.JTextField();
        txtgastos = new javax.swing.JTextField();
        txtneto = new javax.swing.JTextField();
        panel3 = new java.awt.Panel();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setTitle("CIERRE DIARIO");

        lb_fech_act_cierred1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_fech_act_cierred1.setText("Fecha Actual: ");

        lb_id_recep_cierr_d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_id_recep_cierr_d1.setText("Recepcionista:");

        lb_turn_cierr_d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_turn_cierr_d1.setText("Turno:");

        cmbturno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbturno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Completo" }));
        cmbturno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbturnoActionPerformed(evt);
            }
        });

        txtrecepcionista.setEditable(false);
        txtrecepcionista.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrecepcionista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecepcionistaActionPerformed(evt);
            }
        });

        txtfecha.setEditable(false);
        txtfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfechaActionPerformed(evt);
            }
        });

        lb_mont_reca_cierr_d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_mont_reca_cierr_d1.setText("Monto Recaudado:");

        lb_montN_cierr_d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_montN_cierr_d1.setText("Monto Neto:");

        lb_gast_cierr_d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_gast_cierr_d1.setText("Gastos:");

        txtrecaudado.setEditable(false);
        txtrecaudado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtrecaudado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrecaudadoActionPerformed(evt);
            }
        });
        txtrecaudado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrecaudadoKeyTyped(evt);
            }
        });

        txtgastos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtgastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgastosActionPerformed(evt);
            }
        });
        txtgastos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgastosKeyTyped(evt);
            }
        });

        txtneto.setEditable(false);
        txtneto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtneto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_fech_act_cierred1)
                    .addComponent(lb_id_recep_cierr_d1)
                    .addComponent(lb_turn_cierr_d1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbturno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_gast_cierr_d1)
                    .addComponent(lb_mont_reca_cierr_d1)
                    .addComponent(lb_montN_cierr_d1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtgastos, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtrecaudado, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtneto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_fech_act_cierred1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_id_recep_cierr_d1)
                            .addComponent(txtrecepcionista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lb_turn_cierr_d1))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtrecaudado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_mont_reca_cierr_d1))
                        .addGap(5, 5, 5)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_gast_cierr_d1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_montN_cierr_d1)
                            .addComponent(cmbturno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnguardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btneditar.setText("Editar");

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnguardar)
                .addGap(35, 35, 35)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btneditar)
                    .addComponent(btnsalir))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtrecepcionistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecepcionistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecepcionistaActionPerformed

    private void txtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfechaActionPerformed

    private void txtrecaudadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrecaudadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrecaudadoActionPerformed

    private void txtgastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgastosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgastosActionPerformed

    private void txtnetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnetoActionPerformed

    private void cmbturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbturnoActionPerformed
        //estado: Mañana,Tarde,Completo
    }//GEN-LAST:event_cmbturnoActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtrecaudadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrecaudadoKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtrecaudadoKeyTyped

    private void txtgastosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgastosKeyTyped
        // TODO add your handling code here:
        int numerocaracteres=5;
        char d=evt.getKeyChar();
        if (txtgastos.getText().length()>=numerocaracteres){
        evt.consume();
        JOptionPane.showMessageDialog(rootPane,"Solo 5 dígitos");
        }
        if (Character.isLetter(d)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo números","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }        
    }//GEN-LAST:event_txtgastosKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cmbturno;
    private javax.swing.JLabel lb_fech_act_cierred1;
    private javax.swing.JLabel lb_gast_cierr_d1;
    private javax.swing.JLabel lb_id_recep_cierr_d1;
    private javax.swing.JLabel lb_montN_cierr_d1;
    private javax.swing.JLabel lb_mont_reca_cierr_d1;
    private javax.swing.JLabel lb_turn_cierr_d1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtgastos;
    private javax.swing.JTextField txtneto;
    private javax.swing.JTextField txtrecaudado;
    private javax.swing.JTextField txtrecepcionista;
    // End of variables declaration//GEN-END:variables
}
