
package Formulario;

import ClaseConectar.Conectar;
import Clases.fecha;
import static Formulario.alquiler.seleccion_ha;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class reserva extends javax.swing.JInternalFrame {

    Conectar cc=new Conectar();
    Connection cn=cc.conexion();
    public static String bandera_reserva;
    public String usuario_alquiler; 
    public static seleccion_habitacion seleccion_h;
    
    
    
    public reserva() {
        initComponents();
        this.setTitle("RESERVA");
        bandera_reserva="bandera";
        //txtdni.setEnabled(false);
        obt_id();
    }
    public void obt_id(){
        try{
            //obteniendo id de alquila.. id maximo            
            ResultSet rsa;
            Statement sent = cn.createStatement();
            rsa = sent.executeQuery("SELECT IFNULL(MAX(CAST(id_reserva AS UNSIGNED)), 0) codigoExterno FROM hotel_version7.reserva");
            int cont;
            while(rsa.next()){
                cont =Integer.parseInt(rsa.getString("codigoExterno"))+1;
                this.txtidreserva.setText(String.valueOf(cont));
            }            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }      
    }  
    
    public void cerrar(){
        try {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                    confirmarSalida();
                }
            });
        } catch (Exception e) {
        }
    }    
    public void confirmarSalida(){
        int valor=JOptionPane.showConfirmDialog(this,"¿Esta seguro de cerrar la ventana?","Advertencia",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (valor==JOptionPane.YES_OPTION){
            //JOptionPane.showMessageDialog(null,"gracias", "Gracias",JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); 
        }                  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_dt_hab = new javax.swing.JPanel();
        lb_num_hab_alq = new javax.swing.JLabel();
        lb_tip_hab_alq = new javax.swing.JLabel();
        txthabitacion = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        btnbuscarth = new javax.swing.JButton();
        panel_dt_huesp = new javax.swing.JPanel();
        lb_dni_alq = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        lb_nom_alq = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        lb_ape_alq = new javax.swing.JLabel();
        btnbuscarh = new javax.swing.JButton();
        btnhuesped = new javax.swing.JButton();
        panel_datos_reser = new javax.swing.JPanel();
        lb_id_alq = new javax.swing.JLabel();
        lb_fech_lleg = new javax.swing.JLabel();
        lb_fech_sal_reser = new javax.swing.JLabel();
        lb_cant_hab = new javax.swing.JLabel();
        lb_num_camas_hab_alq = new javax.swing.JLabel();
        num_camas_alq = new javax.swing.JTextField();
        lb_mont_tot = new javax.swing.JLabel();
        lb_num_pers_reser = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        txtidreserva = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtadelanto = new javax.swing.JTextField();
        txtpersonas = new javax.swing.JTextField();
        txtdias = new javax.swing.JTextField();
        txtllegada = new com.toedter.calendar.JDateChooser();
        txtsalida = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        btnguardar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();

        panel_dt_hab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE HABITACIÓN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic L", 1, 12))); // NOI18N

        lb_num_hab_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_num_hab_alq.setText("N° Habitación:");

        lb_tip_hab_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_tip_hab_alq.setText("Tipo:");

        txthabitacion.setEditable(false);
        txthabitacion.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        txthabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthabitacionActionPerformed(evt);
            }
        });

        txttipo.setEditable(false);
        txttipo.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N

        btnbuscarth.setText("Buscar");
        btnbuscarth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarthActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dt_habLayout = new javax.swing.GroupLayout(panel_dt_hab);
        panel_dt_hab.setLayout(panel_dt_habLayout);
        panel_dt_habLayout.setHorizontalGroup(
            panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dt_habLayout.createSequentialGroup()
                .addGroup(panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_dt_habLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_tip_hab_alq)
                            .addComponent(lb_num_hab_alq))
                        .addGap(14, 14, 14)
                        .addGroup(panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txthabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_dt_habLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnbuscarth, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel_dt_habLayout.setVerticalGroup(
            panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dt_habLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_num_hab_alq))
                .addGap(18, 18, 18)
                .addGroup(panel_dt_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_tip_hab_alq)
                    .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbuscarth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_dt_huesp.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DEL HUÉSPED", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic L", 1, 12))); // NOI18N
        panel_dt_huesp.setForeground(java.awt.Color.white);
        panel_dt_huesp.setToolTipText("");
        panel_dt_huesp.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N

        lb_dni_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_dni_alq.setText("DNI:");

        txtdni.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniKeyTyped(evt);
            }
        });

        lb_nom_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_nom_alq.setText("Nombres:");

        txtnombres.setEditable(false);
        txtnombres.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });

        txtapellidos.setEditable(false);
        txtapellidos.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });

        lb_ape_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_ape_alq.setText("Apellidos:");

        btnbuscarh.setText("Buscar");
        btnbuscarh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarhActionPerformed(evt);
            }
        });

        btnhuesped.setText("Nuevo Huesped");
        btnhuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_dt_huespLayout = new javax.swing.GroupLayout(panel_dt_huesp);
        panel_dt_huesp.setLayout(panel_dt_huespLayout);
        panel_dt_huespLayout.setHorizontalGroup(
            panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dt_huespLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_dt_huespLayout.createSequentialGroup()
                        .addComponent(lb_dni_alq)
                        .addGap(49, 49, 49)
                        .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuscarh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnhuesped, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_dt_huespLayout.createSequentialGroup()
                        .addGroup(panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_dt_huespLayout.createSequentialGroup()
                                .addComponent(lb_ape_alq)
                                .addGap(18, 18, 18)
                                .addComponent(txtapellidos))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_dt_huespLayout.createSequentialGroup()
                                .addComponent(lb_nom_alq)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_dt_huespLayout.setVerticalGroup(
            panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dt_huespLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscarh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_dni_alq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_nom_alq)
                    .addComponent(txtnombres, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_dt_huespLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_ape_alq)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        panel_datos_reser.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DATOS DE RESERVA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic L", 1, 12))); // NOI18N
        panel_datos_reser.setLayout(null);

        lb_id_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_id_alq.setText("ID Reserva:");
        panel_datos_reser.add(lb_id_alq);
        lb_id_alq.setBounds(20, 60, 80, 20);

        lb_fech_lleg.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_fech_lleg.setText("Fecha Llegada:");
        panel_datos_reser.add(lb_fech_lleg);
        lb_fech_lleg.setBounds(20, 100, 85, 16);

        lb_fech_sal_reser.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_fech_sal_reser.setText("Fecha Salida:");
        panel_datos_reser.add(lb_fech_sal_reser);
        lb_fech_sal_reser.setBounds(20, 140, 75, 16);

        lb_cant_hab.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_cant_hab.setText("N° Días:");
        panel_datos_reser.add(lb_cant_hab);
        lb_cant_hab.setBounds(310, 100, 46, 16);

        lb_num_camas_hab_alq.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_num_camas_hab_alq.setText("Monto Adelantado:");
        lb_num_camas_hab_alq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lb_num_camas_hab_alqKeyTyped(evt);
            }
        });
        panel_datos_reser.add(lb_num_camas_hab_alq);
        lb_num_camas_hab_alq.setBounds(310, 140, 182, 16);

        num_camas_alq.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        panel_datos_reser.add(num_camas_alq);
        num_camas_alq.setBounds(1409, 158, 160, 25);

        lb_mont_tot.setText("Monto Total:");
        panel_datos_reser.add(lb_mont_tot);
        lb_mont_tot.setBounds(1661, 76, 61, 14);

        lb_num_pers_reser.setFont(new java.awt.Font("URW Gothic L", 0, 12)); // NOI18N
        lb_num_pers_reser.setText("N° Personas:");
        panel_datos_reser.add(lb_num_pers_reser);
        lb_num_pers_reser.setBounds(310, 60, 74, 16);

        jTextField1.setText("jTextField1");
        panel_datos_reser.add(jTextField1);
        jTextField1.setBounds(1409, 42, 59, 20);

        txtidreserva.setEditable(false);
        panel_datos_reser.add(txtidreserva);
        txtidreserva.setBounds(120, 50, 120, 30);

        jTextField4.setText("jTextField4");
        panel_datos_reser.add(jTextField4);
        jTextField4.setBounds(1409, 76, 160, 20);

        txtadelanto.setFont(new java.awt.Font("URW Gothic L", 0, 14)); // NOI18N
        txtadelanto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadelantoKeyTyped(evt);
            }
        });
        panel_datos_reser.add(txtadelanto);
        txtadelanto.setBounds(420, 130, 116, 25);

        txtpersonas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpersonasKeyTyped(evt);
            }
        });
        panel_datos_reser.add(txtpersonas);
        txtpersonas.setBounds(420, 50, 117, 30);

        txtdias.setEditable(false);
        txtdias.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        txtdias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiasKeyTyped(evt);
            }
        });
        panel_datos_reser.add(txtdias);
        txtdias.setBounds(420, 90, 116, 27);
        panel_datos_reser.add(txtllegada);
        txtllegada.setBounds(120, 90, 140, 30);
        panel_datos_reser.add(txtsalida);
        txtsalida.setBounds(120, 130, 140, 30);

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btnnuevo.setText("Nuevo");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(148, 148, 148))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_dt_huesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_dt_hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(panel_datos_reser, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(panel_dt_hab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(panel_dt_huesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel_datos_reser, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txthabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthabitacionActionPerformed

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        btnguardar.setEnabled(false);
        btnnuevo.setEnabled(true); 
        btneditar.setEnabled(true);
        /*if(txtpersonas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingresa Cantidas de Personas","ERROR",JOptionPane.ERROR_MESSAGE);
        }else   if (txtsalida.getDate()==null) {
            JOptionPane.showMessageDialog(null,"Ingresa Fecha Salida","ERROR",JOptionPane.ERROR_MESSAGE);
        }else   if (txtllegada.getDate()==null) {
            JOptionPane.showMessageDialog(null,"Ingresa Fecha Salida","ERROR",JOptionPane.ERROR_MESSAGE);
        }else if(txttipo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Elije habitacion","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            try
            {
               PreparedStatement pst=cn.prepareStatement("INSERT INTO hotel_version7.reserva (id_reserva,fecha_llega_rese,"
                    + "fecha_sali_rese,nro_persona_rese,mon_adelanto,nro_dias,num_habita_rese,huesped_dni_huesped) VALUES (?,?,?,?,?,?,?,?)");
                pst.setString(1,txtidreserva.getText());
                pst.setString(2,fecha.getFecha(txtllegada));
                pst.setString(3,fecha.getFecha(txtsalida));
                pst.setString(4,txtpersonas.getText());
                pst.setString(5,txtadelanto.getText());
                pst.setString(6,txtdias.getText());
                pst.setString(7,txthabitacion.getText());
                pst.setString(8,txtdni.getText());
                int a=pst.executeUpdate();
                //
                String habb=txthabitacion.getText();
                PreparedStatement pst1=cn.prepareStatement("UPDATE hotel_version7.habitacion SET estado='Ocupado' WHERE nro_hab='"+habb+"'");
                int b=pst1.executeUpdate();
                if((a>0)&&(b>0)){
                    btnnuevo.setEnabled(true);
                    btnguardar.setEnabled(false);
                    txtdni.setEnabled(false);
                    JOptionPane.showMessageDialog(null,"registro exitoso ");
                    //obtenar cantidad de personas para abrir formato
                    int personas=Integer.parseInt(txtpersonas.getText());
                }
                else{
                    JOptionPane.showMessageDialog(null,"error al agregar ");
                }
            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, "error al agegar datos en reserva " +e);
            }//fin trycatch
        }
        ///*/
        
        
         
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        btnnuevo.setEnabled(false);
        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
    }//GEN-LAST:event_btneditarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        // TODO add your handling code here:
   
        txtdni.setEnabled(false);
        btnguardar.setEnabled(true);
        btneditar.setEnabled(false);
        btnnuevo.setEnabled(false);
      
        txtdni.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        txthabitacion.setText("");
        txtadelanto.setText("");
        txttipo.setText("");
        txtidreserva.setText("");
        txtpersonas.setText(""); 
        txtdias.setText("");
        txtllegada.setDate(new Date());
        txtsalida.setDate(new Date());
        
           
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        cc.desconectar();
        bandera_reserva=null;
        this.dispose();   
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        // TODO add your handling code here:
        
        int numerocaracteres=25;
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingresar solo letras","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
        if (txtnombres.getText().length()>=numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de digitos","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        // TODO add your handling code here:
        
        int numerocaracteres=25;
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingresar solo letras","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
        if (txtapellidos.getText().length()>=numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de digitos","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtdniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyTyped
        // TODO add your handling code here:
        int numerocaracteres=8;
        char d = evt.getKeyChar();
        if (Character.isLetter(d))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingresar solo letras","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
        if (txtdni.getText().length()!=numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"numero de digitos incorrecto","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtdniKeyTyped

    private void txtpersonasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpersonasKeyTyped
        // TODO add your handling code here:
        int numerocaracteres=1;
        char c = evt.getKeyChar(); 
        if (Character.isLetter(c)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingresar solo numeros","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
        if (txtpersonas.getText().length()>=numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de digitos","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtpersonasKeyTyped

    private void txtdiasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiasKeyTyped
        // TODO add your handling code here:
        int numerocaracteres=2;
        char c = evt.getKeyChar(); 
        if (Character.isLetter(c)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingresar solo numeros","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
        if (txtdias.getText().length()>=numerocaracteres)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null,"Exceso de digitos","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtdiasKeyTyped

    private void txtadelantoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadelantoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar(); 
        if (Character.isLetter(c)) 
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null,"Ingresar solo numeros","¡Advertencia!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtadelantoKeyTyped

    private void btnbuscarthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarthActionPerformed
        // TODO add your handling code here:
       // seleccion_ha=new seleccion_habitacion(this,true);
       // seleccion_ha.setVisible(true);
       
        
        
       
        
    }//GEN-LAST:event_btnbuscarthActionPerformed

    private void btnbuscarhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarhActionPerformed
        // TODO add your handling code here:
        //txtdni.setEnabled(true);
        if (txtdni.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Ingresa DNI","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else
        {            
            String dni= (txtdni.getText());        
            try{          
                ResultSet rs1;
                PreparedStatement pst=cn.prepareStatement("SELECT nombre_h,apellidos_h FROM hotel_version7.huesped where dni_huesped='"+dni+"'");
                rs1 = pst.executeQuery();//buscando datos y guardando en interfaz                                
                while(rs1.next()){                    
                    txtnombres.setText(rs1.getString("nombre_h"));
                    txtapellidos.setText(rs1.getString("apellidos_h"));                    
                }
                if (txtnombres.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"No existe ese DNI","ERROR",JOptionPane.ERROR_MESSAGE);
                }else{
                    btnbuscarth.setEnabled(true);
                    btnguardar.setEnabled(true);
                }                   
            }catch(HeadlessException | SQLException e){
                System.err.println("No se pudo buscar");
            }
        }
    }//GEN-LAST:event_btnbuscarhActionPerformed

    private void lb_num_camas_hab_alqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lb_num_camas_hab_alqKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lb_num_camas_hab_alqKeyTyped

    private void btnhuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuespedActionPerformed
        // TODO add your handling code here:
        String bandera=huesped.bandera_huesped;
        try{            
            if(bandera==null){            
                huesped a= new huesped();
                this.getDesktopPane().add(a);
                a.setVisible(true);            
            }else{
                JOptionPane.showMessageDialog(rootPane,"La ventana ya esta abierta!");
            }    
        }catch(Exception e){
            e.printStackTrace();    
        }
    }//GEN-LAST:event_btnhuespedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscarh;
    private javax.swing.JButton btnbuscarth;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnhuesped;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton btnsalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lb_ape_alq;
    private javax.swing.JLabel lb_cant_hab;
    private javax.swing.JLabel lb_dni_alq;
    private javax.swing.JLabel lb_fech_lleg;
    private javax.swing.JLabel lb_fech_sal_reser;
    private javax.swing.JLabel lb_id_alq;
    private javax.swing.JLabel lb_mont_tot;
    private javax.swing.JLabel lb_nom_alq;
    private javax.swing.JLabel lb_num_camas_hab_alq;
    private javax.swing.JLabel lb_num_hab_alq;
    private javax.swing.JLabel lb_num_pers_reser;
    private javax.swing.JLabel lb_tip_hab_alq;
    private javax.swing.JTextField num_camas_alq;
    private javax.swing.JPanel panel_datos_reser;
    private javax.swing.JPanel panel_dt_hab;
    private javax.swing.JPanel panel_dt_huesp;
    private javax.swing.JTextField txtadelanto;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtdias;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txthabitacion;
    private javax.swing.JTextField txtidreserva;
    private com.toedter.calendar.JDateChooser txtllegada;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtpersonas;
    private com.toedter.calendar.JDateChooser txtsalida;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
